### ISSUE TITLE
error with the pack isssue when trying to add stickers

### ISSUE THREAD

**Issue by anand0249** [midhunhk/ae-sticker-app#14]
![image](https://user-images.githubusercontent.com/91336664/167253861-db49b3f2-cc80-47d2-ba94-b1039bf26ab7.png)

**Comment by midhunhk** [comment]
Please see the below issue on the official WhatsApp Sticker repo

https://github.com/WhatsApp/stickers/issues/537


"The problem occurred when whatsapp was installed in my sd card. Moving it back to the internal storage fixed the problem but needing to ask each user to move whatsapp back to the internal storage is not a true fix."
- https://github.com/WhatsApp/stickers/issues/537#issuecomment-749217858

**Comment by anand0249** [comment]
> Please see the below issue on the official WhatsApp Sticker repo
> 
> [WhatsApp/stickers#537](https://github.com/WhatsApp/stickers/issues/537)
> 
> "The problem occurred when whatsapp was installed in my sd card. Moving it back to the internal storage fixed the problem but needing to ask each user to move whatsapp back to the internal storage is not a true fix."
> 
> * [Requires com.whatsapp.sticker.READ or grantUriPermission() Error WhatsApp/stickers#537 (comment)](https://github.com/WhatsApp/stickers/issues/537#issuecomment-749217858)

I didnt try to install it in my sd card first of all i dont have my sd card with me now
😭
