### ISSUE TITLE
error: cannot access AnimatedImage class file for com.facebook.imagepipeline.animated.base.AnimatedImage not found

### ISSUE THREAD

**Issue by billyjoker** [midhunhk/ae-sticker-app#3]
Details explained here:
https://stackoverflow.com/questions/54427681/error-cannot-access-animatedimage-class-file-for-com-facebook-imagepipeline-ani

Also the solution, a missed library:

implementation 'com.facebook.fresco:animated-base:1.13.0'

**Comment by kabirhafeez** [comment]
Where to get the JSON file for the project? Do we need to create a new project on firebase?

**Comment by midhunhk** [comment]
Yes, you need to configure firebase for your app. I haven't checked in my JSON file. Else you can comment out the related declarations etc.

I have checked in a stub version used for debug builds at:
https://github.com/midhunhk/ae-sticker-app/blob/master/app/src/dev/google-services.json
