### ISSUE TITLE
Can u make it JSON remote if possible 

### ISSUE THREAD

**Issue by venky1995** [midhunhk/ae-sticker-app#8]
Can u make it JSON from server side or GitHub by replacing assets. Thankyou

**Comment by midhunhk** [comment]
Hi Venky,

Thanks for your posting this query. This StickersApp is based on the sample app shared by the WhatsApp Team - https://github.com/WhatsApp/stickers/tree/master/Android.

This app loads the json file from the **/assets** folder in the file **StickerPackLoader.java**. I think the assets need to be part of the APK as they are queried with the "ContentProvider".
