### ISSUE TITLE
how to remove firebase

### ISSUE THREAD

**Issue by kali517** [midhunhk/ae-sticker-app#9]
how to remove firebase from this new project?

**Comment by midhunhk** [comment]
Hello

Firebase is used to provide Analytics in this project . You could clone this project and remove the following items and their references.

project level build.gradle
  > implementation 'com.google.firebase:firebase-core:18.0.0'

The below java file
 > app/src/main/java/com/ae/apps/stickerapp/analytics/Analytics.java

Also remove all references to `Analytics`

Check if these solve your need, or let me know if there are any issues.

**Comment by midhunhk** [comment]
Closing for now, reopen or add a comment incase you need more help.
